name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Org Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Personal Repo
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git remote add personal https://x-access-token:${PERSONAL_TOKEN}@github.com/AdrianeDriane/vista-frontend.git
          git push personal main --force
